### ISSUE TITLE
BLAT search not working

### ISSUE THREAD

**Issue by marc-sturm** [igvteam/igv#1062]
Hi,

we are using IGV 2.10.3 for Windows behind a authenticating proxy and the BLAT search is not working:
![grafik](https://user-images.githubusercontent.com/5638144/144568632-9025cb24-822b-4961-9d7b-99f5cca936a6.png)

If I use the same IGV on a different network without a proxy, the BLAT search is working.

I guess the BLAT search access a NCBI webservice and maybe the proxy is not used correctly for this connection?

Unfortunately no log file is generated in the C:\users\[user]\.igv\ folder, so I cannot provide more information.

Best,
  Marc

**Comment by jrobinso** [comment]
Blat uses a UCSC webservice.   Also, that is not where the log file is generated, its in the "igv" folder not the ".igv" folder.

I can't really help debugging your proxy, but you can see the blat URL in the "advanced" prefences.   It changed at some point and I don't recall what was used with 2.10.3 but select "View > Prferences > Advanced" and you will see it.

**Comment by marc-sturm** [comment]
Hi Jim,

The URL used is this:
https://genome.ucsc.edu/cgi-bin/hgBlat?userSeq=$SEQUENCE&type=DNA&db=$DB&output=json
If I use it in a browser, the URL works.

https://genome.ucsc.edu/cgi-bin/hgBlat?userSeq=GGAGAAGTTTAATTTACACAACGAT&type=DNA&db=hg19&output=json
returns
`{ "track": "blat", "genome": "hg19", "fields": ["matches", "misMatches", "repMatches", "nCount", "qNumInsert", "qBaseInsert", "tNumInsert", "tBaseInsert", "strand", "qName", "qSize", "qStart", "qEnd", "tName", "tSize", "tStart", "tEnd", "blockCount", "blockSizes", "qStarts", "tStarts"], "blat" : [ [25,0,0,0,0,0,0,0,"+","YourSeq",25,0,25,"chr17",81195210,41223267,41223292,1,"25","0","41223267"] ] }`

Thanks for pointing me to the correct log folder.
The log contains this error:
`ERROR [2021-12-04T16:16:51,662] [MessageUtils.java:66]  Error running blat
org.broad.igv.exceptions.HttpResponseException: Proxy Authentication Required
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:902) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:649) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:645) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.getContentsAsJSON(HttpUtils.java:254) ~[igv.jar:?]
	at org.broad.igv.util.blat.BlatClient.blat(BlatClient.java:90) ~[igv.jar:?]
	at org.broad.igv.util.blat.BlatClient$1.run(BlatClient.java:148) [igv.jar:?]
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72) [igv.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
ERROR [2021-12-04T16:16:51,693] [MessageUtils.java:76]  Error running blat`

Is it possible the authentification is not correctly handled for the BLAT request?
The proxy credentials are in the settings and downloading genomes works.

Best,
  Marc

**Comment by jrobinso** [comment]
OK, a couple of things to try.

First in the "Proxy" tab of the preferences window try checking "Disable check for system proxy".

If that doesn't work, uncheck it and try UNCHECKING "User proxy".   Although that might seem counter-intuitive, it sometimes causes Java to use built in proxy settings from some magic place.   

These 2 suggestions do essentially opposite things, the first disables any check for system defined proxy and forces use of the IGV settings,  the second disables use of IGV settings and (hopefully) forces use of system settings, that is the same settings the browser uses.


<img width="443" alt="Screen Shot 2021-12-04 at 5 38 53 PM" src="https://user-images.githubusercontent.com/933148/144726671-3dd85d86-513b-4e87-8b1a-7789b1c3b2a1.png">

**Comment by marc-sturm** [comment]
I tried both setting options and restared IGV in between, but the error remains.
In both modes I can download genomes though.

I could try and ask out IT guys to check the firewall logs...

**Comment by jrobinso** [comment]
@marc-sturm yes I would recommend that.   The message indicates that IGV (i.e. Java) is getting a "407" response code for the request to the blat server.

**Comment by jrobinso** [comment]
@marc-sturm I might have found the issue, I had to write my own proxy server to debug this.  I think the problem is using basic authentication with the proxy to access https resources.   This has apparently been disabled by default, which I was unaware of.   I'm looking into possible workarounds on the IGV side.   I am assuming your proxy server is using basic authentication since that is what IGV supports through the user preferences.

**Comment by jrobinso** [comment]
@marc-sturm Its not clear that there is going to be a solution for the general problem, that is supporting https requests through a proxy with basic authentication.   However I have a workaround for blat.  Simply edit the blat URL in the users preferences to use "http" protocol, i.e. change the value to this

```
http://genome.ucsc.edu/cgi-bin/hgBlat?userSeq=$SEQUENCE&type=DNA&db=$DB&output=json
```

Let me know if that works.

**Comment by marc-sturm** [comment]
Using http protocol instead of https for BLAT works fine. Thanks for the hint.

It would be great if you could get basic authentication for https running as well.
I could support you by testing only though.
My java is really bad. I'm a C++ guy :)

**Comment by marc-sturm** [comment]
Our admin found out that if you comment out the line `jdk.http.auth.tunneling.disabledSchemes=Basic` in `net.properties` of JDK it works with https as well!

**Comment by jrobinso** [comment]
@marc-sturm That's really good information,  I'm not sure we can use it for general distribution but will look into it.

I deployed another fix for https last night, if you could test the nightly snapshot with an https blat url (and without commenting out the line in net.properties) it would help us a lot.   I wrote a simple proxy to try to emulate your situation but it is a poor substitute for the real thing.

**Comment by jrobinso** [comment]
And BTW getting https to work generally with your proxy is important as their are many other resources that are loaded by https (in addition to blat).

**Comment by marc-sturm** [comment]
Unfortunaltely BLAT still does not work.
But the error message changed:
![grafik](https://user-images.githubusercontent.com/5638144/145596970-c071b437-efb1-4419-90ef-f81e307c0f3c.png)

Here the proxy settings:
![grafik](https://user-images.githubusercontent.com/5638144/145597884-241ac684-491c-4808-9fc6-cf282eca9342.png)

And the log entry:
![grafik](https://user-images.githubusercontent.com/5638144/145598157-b8cbb01c-fd17-4c79-8581-e16e4e2193ab.png)

**Comment by jrobinso** [comment]
OK -- thanks for testing.   So the only solution to this is the one your admin found, specifically commenting out the line ```jdk.http.auth.tunneling.disabledSchemes=Basic```  in ```$JAVA_HOME/conf/net.properties```.   It does not work, on my machine at least, to try setting this on the command line (with -D) or in code.    So I'm going to close this as there is no other solution, for now at least, than commenting out that line.
