### ISSUE TITLE
Remove Track fails to release a handle on the track

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#748]
I find that after running IGV latest under windows "Track > Right Click > Remove Track" I am unable to delete the track using windows file-system instead getting error dialog:

![image](https://user-images.githubusercontent.com/484282/72864927-78a68d80-3c9b-11ea-8822-6dcad0953de0.png)

**Comment by jrobinso** [comment]
Interesting.   Do you know when (version) this problem first appeared, or put another way what version were you using successfully before trying the latest one?

**Comment by malcook** [comment]
I’m unsure but it has been for years.  I thought I had reported it but could not find the report.  If I quit IGV I can immediate delete the file.  It may be an interaction with our storage in some strange way.  I can not delete such a file from my windows client (which is running IGV) but can go around the back and delete it from unix side.  Not being a storage guy, I can't chalk this up to anything specific.  Thanks for caring though.

By the way, I've often wished I could get IGV to reload a file that has been re-written.  I hoped the "reload session" was going to accomplish this for me, but it appears not.  Perhaps relate issue.  Perhaps both operator error?

Cheers

**Comment by jrobinso** [comment]
Sorry for the delay on this, I've not been able to reproduce it on my Mac but I just noticed your screenshot references an ".igv" file.  Was the error specific to that file type?  If so it might be fixed, I found that the parser for those files was not closing the stream.   There are a zillion parsers now and I'm not going to check them all, at least not right away,  but for that file type you shouldn't see it anymore.    Re your other wish there are "reload session" and "reload tracks" options,  the "reload session" option is only active you if have loaded or saved a session.   The behavior differs, reloading a session will do just that, resetting all state,  reloading tracks will not reset any other state.

**Comment by malcook** [comment]
I just now tried it with a .igv.tdf file and got the same behavior. Do you have a QA team with windows to try and reproduce?  I tried it with the file on PC's local drive as well as remote mount and it happens with both.

**Comment by jrobinso** [comment]
OK I'll look at TDF files.  Tried it with what IGV version?     QA team?  at your service.

**Comment by jrobinso** [comment]
BTW it doesn't matter what version you were using, I only addressed ".igv" files in the last push,  not ".tdf" files.

**Comment by jrobinso** [comment]
I've cleanup up .igv, .tdf, and bigwig files.  Unfortunately a lot of formats are read by the htsjdk, including feature formats like bed, vcf, and bam files.   Its not clear to me at the moment, from code inspection, how file handles are closed there but I will give it a fresh look later.

**Comment by malcook** [comment]
I've tried .igv.tdf in nightly (windows 10) and find somewhat disconcertedly that I can now delete the file while it is displayed in IGV.

My expectation/hope was that files open in IGV would continue to be locked against deletion, but that once the track(s) in the file are (all) removed from IGV's display, the file could be deleted from the filesystem.  Is this your intention? If so, there remains work to be done.

**Comment by malcook** [comment]
BTW, I also notice in nightly that track labels now include the full path to the file... 
![image](https://user-images.githubusercontent.com/484282/104480437-2f290f80-558a-11eb-96c6-047f1cdc8182.png)

is this intentional?

**Comment by jrobinso** [comment]
@I will fix the names.   I am not going to try to manage locks on files,  as this has proven error prone.

**Comment by jrobinso** [comment]
@malcook The problem you're seeing with sample names is curious,  I'm not seeing it,  could you possibly share that file?

**Comment by malcook** [comment]
> could you possibly share that file?

https://research.stowers.org/mec/H3K9me3.igv.tdf

in my hands, it only occurs in nightly, and only when loaded from filesystem (both local harddrive or smb mount) 

notably, it does NOT display this way when loaded from URL

**Comment by jrobinso** [comment]
Sample name problem should be fixed.  Files are closed on track removal for some but not all file types.  There is not a 1-1 correspondence between track and file,  this is complex, but I'm punting to the next release to look at remaining file types.

**Comment by eroller** [comment]
This still happens with the bam index (bam.bai) file although the bam file seems to be released. Tried with IGV 2.17.1 on Windows 10.
